AWSTemplateFormatVersion: '2010-09-09'
Description: Template to deploy a Load Balancer

Parameters:
  rELBExternalCouchDBSG:
    Description: "Security Group for Load Balancer"
    Type: String
  PubSubnetZoneA:
    Description: "Private subnet zona A"
    Type: String
  PubSubnetZoneB:
    Description: "Private subnet zona B"
    Type: String
  PubSubnetZoneC:
    Description: "Private subnet zona B"
    Type: String
  rCouchDBInstance01:
    Description: "EC2 instance node 1"
    Type: String
  rCouchDBInstance02:
    Description: "EC2 instance node 2"
    Type: String
  rCouchDBInstance03:
    Description: "EC2 instance node 3"
    Type: String
  VpcId:
    Description: "VPC ID for Security Group"
    Type: String

Resources:
  rLoadBalancerExt:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
          Name: loadbalancer-couchdb-external
          Scheme: internet-facing
          Type: application
          SecurityGroups: 
              - !Ref rELBExternalCouchDBSG
          Subnets:
              - !Ref PubSubnetZoneA
              - !Ref PubSubnetZoneB
              - !Ref PubSubnetZoneC
          Tags: 
              - Key: Name
                Value: loadbalancer-couchdb-external

  rLoadBalancerExtListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
          LoadBalancerArn: !Ref rLoadBalancerExt
          Port: 80
          Protocol: HTTP
          DefaultActions: 
              - Type: forward
                TargetGroupArn: !Ref rTargetGroupExt

  rTargetGroupExt:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
          VpcId: !Ref VpcId
          Port: 5984
          Protocol: HTTP
          Targets:
          - Id: !Ref rCouchDBInstance01
            Port: 5984
          - Id: !Ref rCouchDBInstance02
            Port: 5984
          - Id: !Ref rCouchDBInstance03
            Port: 5984
          Matcher: 
              HttpCode: 200
          HealthCheckIntervalSeconds: 10
          HealthCheckPath: /_up
          HealthCheckProtocol: HTTP
          HealthCheckTimeoutSeconds: 5
          HealthyThresholdCount: 2
          UnhealthyThresholdCount: 2
