AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  S3Bucket: 
    Description: "Name of the S3 bucket for the artifacts of the modules"
    Type: String

Resources:
  ModuleNetworking:
    Type: 'AWS::CloudFormation::ModuleVersion'
    Properties:
      ModuleName: 'SMENETWORKING::EC2::VPC::MODULE'
      ModulePackage: !Sub 's3://${S3Bucket}/smenetworking-ec2-vpc-module.zip'

  ModuleSecurityGroup:
    Type: 'AWS::CloudFormation::ModuleVersion'
    Properties:
      ModuleName: 'SMESECURITYGROUP::EC2::VPC::MODULE'
      ModulePackage: !Sub 's3://${S3Bucket}/smesecuritygroup-ec2-vpc-module.zip'

  ModuleEC2:
    Type: 'AWS::CloudFormation::ModuleVersion'
    Properties:
      ModuleName: 'SMEEC2::EC2::VPC::MODULE'
      ModulePackage: !Sub 's3://${S3Bucket}/smeec2-ec2-vpc-module.zip'

  ModuleALB:
    Type: 'AWS::CloudFormation::ModuleVersion'
    Properties:
      ModuleName: 'SMEALB::EC2::ALB::MODULE'
      ModulePackage: !Sub 's3://${S3Bucket}/smealb-ec2-alb-module.zip'
